server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sz_busi_monitor?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sc990912
mybatis:
  mapper-locations: classpath*:mapper/*.xml
